name: system_shortcuts
description: Flutter plugin to use system shortcuts like pressing home, back, volume Up, volume Down keys and toggle wifi, and bluetooth as well. 
version: 0.2.2
homepage: https://github.com/aman-malhotra-1999/SystemShortcutsFlutter

environment:
  sdk: ">=2.0.0 <3.0.0"
  flutter: ^1.10.0

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.example.systemshortcuts
        pluginClass: SystemShortcutsPlugin

